##===- klang/lib/Parse/Makefile ----------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##
#
#  This implements the Parse library for the Kaleidoscope front-end.
#
##===----------------------------------------------------------------------===##


#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of a library.  This will build a dynamic version.
#
LIBRARYNAME=klangParse

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common
