##===- klang/tools/Makefile --------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##
#
#  This implements the executable for the Kaleidoscope front-end.
#
##===----------------------------------------------------------------------===##


#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=driver

include $(LEVEL)/Makefile.common
